name: auth_api
description: Package for A.P.I related operations on authentication operations and service
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  env_flutter: ^0.1.4
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.25

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
