// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA2JR0z3zxNLCdQYUEbrJbD32nh2cWVa4',
    appId: '1:54711469607:web:fa934537be020aa379b002',
    messagingSenderId: '54711469607',
    projectId: 'doccare-d9be1',
    authDomain: 'doccare-d9be1.firebaseapp.com',
    storageBucket: 'doccare-d9be1.appspot.com',
    measurementId: 'G-3MXD2VMVMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb-_ptCqkrAnMfrSWL5F-XcdzorWMSHqo',
    appId: '1:54711469607:android:5ab1668d90cae02679b002',
    messagingSenderId: '54711469607',
    projectId: 'doccare-d9be1',
    storageBucket: 'doccare-d9be1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFoUhRPDDGk-BflKj-PD1aOiyvG_9DSCY',
    appId: '1:54711469607:ios:f28e767558da6b1f79b002',
    messagingSenderId: '54711469607',
    projectId: 'doccare-d9be1',
    storageBucket: 'doccare-d9be1.appspot.com',
    iosBundleId: 'com.example.src',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFoUhRPDDGk-BflKj-PD1aOiyvG_9DSCY',
    appId: '1:54711469607:ios:e4afb907e9e2b65a79b002',
    messagingSenderId: '54711469607',
    projectId: 'doccare-d9be1',
    storageBucket: 'doccare-d9be1.appspot.com',
    iosBundleId: 'com.example.src.RunnerTests',
  );
}
