name: components
description: Packages for components
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  extensions:
    path: ../extensions
  controllers:
    path: ../controllers
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  flutter_bloc: ^8.1.3
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
