name: screens
description: Package for screens in this application
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  auth_api:
    path: ../authentication/auth_api
  auth_domain:
    path: ../authentication/auth_domain
  bloc: ^8.1.2
  components:
    path: ../components
  equatable: ^2.0.5
  extensions:
    path: ../extensions
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  meta: ^1.9.1
  models:
    path: ../models
  model_api:
    path: ../model_api
  utility:
    path: ../utility

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
