name: screens
description: Package for screens in this application
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  auth_api:
    path: ../authentication/auth_api
  auth_domain:
    path: ../authentication/auth_domain
  administrator:
    path: ../administrator
  bloc: ^8.1.2
  pdf: ^3.8.2
  path_provider: ^2.0.5
  open_file: ^3.1.0
  fl_chart: ^0.64.0
  screenshot: ^2.1.0
  permission_handler: ^9.2.0
  components:
    path: ../components
  equatable: ^2.0.5
  extensions:
    path: ../extensions
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  meta: ^1.9.1
  models:
    path: ../models
  utility:
    path: ../utility

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
