name: model_api
description: Package for A.P.I related operations on models
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  env_flutter: ^0.1.4
  flutter:
    sdk: flutter
  http: ^1.1.0
  models:
    path: ../models
  supabase_flutter: ^1.10.24

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
