name: auth_domain
description: Package for authentication repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auth_api:
    path: ../auth_api
  models:
    path: ../../models
  supabase_flutter: ^1.10.25
dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
